services:
  app-api:
    image: jaylordibe/laravel-php:8.5
    container_name: ${SERVICE_NAME}-api
    restart: unless-stopped
    tty: true
    platform: linux/amd64
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - app-db
      - app-redis
    networks:
      - app-network
  app-db:
    image: mysql:8.0.25
    container_name: ${SERVICE_NAME}-db
    restart: unless-stopped
    tty: true
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/database/data:/var/lib/mysql
    networks:
      - app-network
  app-db-gui:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${SERVICE_NAME}-db-gui
    restart: unless-stopped
    tty: true
    platform: linux/amd64
    ports:
      - "8001:80"
    environment:
      PMA_HOST: app-db
      UPLOAD_LIMIT: 300M
    networks:
      - app-network
  app-db-test:
    image: mysql:8.0.25
    container_name: ${SERVICE_NAME}-db-test
    restart: unless-stopped
    tty: true
    platform: linux/amd64
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TEST_DB_DATABASE}
      MYSQL_USER: ${TEST_DB_USERNAME}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
    volumes:
      - ./docker/database/test-data:/var/lib/mysql
    networks:
      - app-network
  app-db-test-gui:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${SERVICE_NAME}-db-test-gui
    restart: unless-stopped
    tty: true
    platform: linux/amd64
    ports:
      - "8002:80"
    environment:
      PMA_HOST: app-db-test
      UPLOAD_LIMIT: 300M
    networks:
      - app-network
  app-redis:
    image: redis:latest
    container_name: ${SERVICE_NAME}-redis
    ports:
      - "6378:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
